# Configuration constants for the organism simulation

# Grid & organisms
WORLD_SIZE = 16
ORGANISM_COUNT = 1
SEED_ORGANISM_ENERGY = 0.4
# Hyperparameters
CNN_HIDDEN_CHANNELS = 3
REPRODUCTION_THRESHOLD = 0.1
DEATH_THRESHOLD = 0.05

# Thermodynamics (single Onsager conductance; κ splits channels)
THERMO_ENV_TEMPERATURE = 1.0
ENTROPY_EPSILON = 1e-8
THERMO_CONDUCTANCE = 0.05
THERMO_ETA = 1.0
PUMP_KAPPA_TERRAIN = 1.0
PUMP_KAPPA_NEIGH = 0.15
SPECTRUM_CONSUMER_EPSILON = 1e-6

# CNN evolution
CNN_POPULATION_SIZE = 16
CNN_MUTATION_RATE = 0.01
CNN_MUTATION_MAGNITUDE = 0.5
CNN_TRAINING_EPOCHS = 100
CNN_TRAINING_MAX_TIME = 100
CNN_FITNESS_MODE = "life_like"
CNN_FITNESS_PERSISTENCE_TERRAIN = 0.5
CNN_FITNESS_LIFE_LIKE_ORDER_WEIGHT = 1.0
CNN_FITNESS_LIFE_LIKE_ENTROPY_FLOOR = 0.0
TRAIN_HEADLESS = True
TRAIN_WORKER_COUNT = 8
TRAIN_WORKER_MAX_TASKS = 1

# Environment (1=center mask, 2=perlin pump, 3=moving perlin)
ENVIRONMENT_TYPE = 2
ENV_NOISE_THRESHOLD = 0
NOISE_OCTAVES = 6
NOISE_POWER = 1
PERLIN_SEED = 234
PERLIN_NOISE_SCALE = 0.1
PERLIN_TIME_SPEED = 0.1
TERRAIN_ENERGY_SCALE = 0.8
STARTING_POSITION_TERRAIN_BOOST = 0.5
TERRAIN_PUMP_ENABLED = True
TERRAIN_PUMP_RATE = 0.1
PUMP_PERLIN_TIME_SPEED = 0.01
PUMP_WAVE_RATE = 0.006
PUMP_WAVE_BIAS = -0.22
PUMP_MEAN_RATE = 0.04
PUMP_TRAIL_RELAX_RATE = 0.01
PUMP_MAX_CELL_DELTA = 0.006
PUMP_POPULATION_FRACTION = 0.25
PUMP_POPULATION_SETPOINT = None
PUMP_PID_KP = 0.45
PUMP_PID_KI = 0.001
PUMP_PID_KD = 0.004
PUMP_PID_DEADBAND = 0.0
PUMP_PID_CLAMP = 1.0
PUMP_PID_INTEGRAL_CLAMP = 4.0
PUMP_DRIVE_SLEW = 0.06
PUMP_PID_OSCILLATION_AMPLITUDE = 1
PUMP_PID_OSCILLATION_PERIOD = 5

# Rendering & runtime
RENDERING_FPS = 30
RENDERING_BASE_FPS = 60
PIXEL_SCALE = 255
PIXEL_SCALE_FACTOR = int(32 / WORLD_SIZE * 20)
OPENGL_CLEAR_COLOR_R = 0.0
OPENGL_CLEAR_COLOR_G = 0.0
OPENGL_CLEAR_COLOR_B = 0.0
OPENGL_CLEAR_COLOR_A = 1.0
GPU_CACHE_CLEAR_INTERVAL = 10
DEVICE_TYPE = "mps"
DEBUG_PRINT_INTERVAL = 10
