# Configuration constants for the organism simulation
import random
# World Configuration
WORLD_SIZE = 500
ORGANISM_COUNT = 1

# Environment Configuration
NOISE_SCALE = 0.01
QUANTIZATION_STEP = 0.01
NOISE_FREQUENCY_MULTIPLIER = 3
NOISE_OCTAVES = 6
NOISE_POWER = 2.2

# Organism Configuration
ENERGY_HARVEST_RATE = 0.01
ENERGY_DECAY = 0.0005
# Spawn organisms in the center of the simulation
CENTER_X = WORLD_SIZE // 2
CENTER_Y = WORLD_SIZE // 2
ORGANISM_POSITIONS = [(CENTER_X, CENTER_Y) for i in range(ORGANISM_COUNT)]

# Reproduction Configuration
REPRODUCTION_THRESHOLD = 0.005
DEATH_THRESHOLD = 0.001

# Energy Configuration
ENERGY_SHARING_RATE = 1


# Rendering Configuration
RENDERING_FPS = 30   # Desired rendering FPS
RENDERING_BASE_FPS = 60  # Base FPS for frequency calculation
PIXEL_SCALE = 255

# OpenGL Configuration
OPENGL_CLEAR_COLOR_R = 0.0
OPENGL_CLEAR_COLOR_G = 0.0
OPENGL_CLEAR_COLOR_B = 0.0
OPENGL_CLEAR_COLOR_A = 1.0

# Performance Configuration
GPU_CACHE_CLEAR_INTERVAL = 10

# Debug Configuration
DEBUG_PRINT_INTERVAL = 10

# CNN Training Configuration
CNN_POPULATION_SIZE = 8
CNN_MUTATION_RATE = 1
CNN_MUTATION_MAGNITUDE = 2
CNN_TRAINING_EPOCHS = 100
CNN_TRAINING_MAX_TIME = 1000
CNN_DEFAULT_EPOCHS = 1000
CNN_DEFAULT_MAX_TIME = 1000
CNN_FITNESS_EARLY_TERMINATION_THRESHOLD = 0.001
CNN_STABILITY_VARIANCE_THRESHOLD = 100.0
CNN_ENERGY_HISTORY_WINDOW = 100
